# Generated by Django 3.1.5 on 2021-01-19 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('town', models.CharField(max_length=250)),
                ('street', models.CharField(max_length=50)),
                ('home_number', models.CharField(max_length=50)),
                ('flat_number', models.IntegerField(null=True)),
                ('post_code', models.CharField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=35)),
                ('last_name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=300)),
                ('adress', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Mail.adress')),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('type', models.CharField(choices=[('private', 'Private'), ('bussines', 'bussines')], max_length=10)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mail.person')),
            ],
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_adress', models.EmailField(max_length=254)),
                ('type', models.CharField(choices=[('private', 'Private'), ('bussines', 'bussines')], max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mail.person')),
            ],
        ),
    ]
