# Generated by Django 3.1.5 on 2021-01-19 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Mail', '0002_auto_20210119_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='adress',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='Mail.adress'),
        ),
    ]
