# Generated by Django 3.1.5 on 2021-01-19 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mail', '0003_auto_20210119_1403'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='adress',
        ),
    ]
