# Generated by Django 3.1.5 on 2021-01-22 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mail', '0005_auto_20210120_1819'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.ManyToManyField(to='Mail.Person')),
            ],
        ),
    ]
