# Generated by Django 3.1.5 on 2021-01-22 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mail', '0006_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='name',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
